/*
 * Copyright (C) 2015 Sergii Pylypenko
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "scancodes.h"

const int scancodes_table[SDL_NUM_SCANCODES] =
{
    0, 0, 0, 0,
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '0',
    SDLK_RETURN,
    SDLK_ESCAPE,
    SDLK_BACKSPACE,
    SDLK_TAB,
    SDLK_SPACE,
    '-',
    '=',
    '[',
    ']',
    '\\',
    '#',
    ';',
    '\'',
    '`',
    ',',
    '.',
    '/',
    SDLK_CAPSLOCK,
    SDLK_F1,
    SDLK_F2,
    SDLK_F3,
    SDLK_F4,
    SDLK_F5,
    SDLK_F6,
    SDLK_F7,
    SDLK_F8,
    SDLK_F9,
    SDLK_F10,
    SDLK_F11,
    SDLK_F12,
    SDLK_PRINT,
    SDLK_SCROLLOCK,
    SDLK_PAUSE,
    SDLK_INSERT,
    SDLK_HOME,
    SDLK_PAGEUP,
    SDLK_DELETE,
    SDLK_END,
    SDLK_PAGEDOWN,
    SDLK_RIGHT,
    SDLK_LEFT,
    SDLK_DOWN,
    SDLK_UP,
    SDLK_NUMLOCK,
    SDLK_KP_DIVIDE,
    SDLK_KP_MULTIPLY,
    SDLK_KP_MINUS,
    SDLK_KP_PLUS,
    SDLK_KP_ENTER,
    SDLK_KP1,
    SDLK_KP2,
    SDLK_KP3,
    SDLK_KP4,
    SDLK_KP5,
    SDLK_KP6,
    SDLK_KP7,
    SDLK_KP8,
    SDLK_KP9,
    SDLK_KP0,
    SDLK_KP_PERIOD,
    0,
    0, //SDLK_APPLICATION,
    SDLK_POWER,
    SDLK_KP_EQUALS,
    SDLK_F13,
    SDLK_F14,
    SDLK_F15,
    0, //SDLK_F16,
    0, //SDLK_F17,
    0, //SDLK_F18,
    0, //SDLK_F19,
    0, //SDLK_F20,
    0, //SDLK_F21,
    0, //SDLK_F22,
    0, //SDLK_F23,
    0, //SDLK_F24,
    0, //SDLK_EXECUTE,
    SDLK_HELP,
    SDLK_MENU,
    0, //SDLK_SELECT,
    0, //SDLK_STOP,
    0, //SDLK_AGAIN,
    SDLK_UNDO,
    0, //SDLK_CUT,
    0, //SDLK_COPY,
    0, //SDLK_PASTE,
    0, //SDLK_FIND,
    0, //SDLK_MUTE,
    0, //SDLK_VOLUMEUP,
    0, //SDLK_VOLUMEDOWN,
    0, 0, 0,
    0, //SDLK_KP_COMMA,
    0, //SDLK_KP_EQUALSAS400,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, //SDLK_ALTERASE,
    SDLK_SYSREQ,
    0, //SDLK_CANCEL,
    SDLK_CLEAR,
    0, //SDLK_PRIOR,
    0, //SDLK_RETURN2,
    0, //SDLK_SEPARATOR,
    0, //SDLK_OUT,
    0, //SDLK_OPER,
    0, //SDLK_CLEARAGAIN,
    0, //SDLK_CRSEL,
    0, //SDLK_EXSEL,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, //SDLK_KP_00,
    0, //SDLK_KP_000,
    0, //SDLK_THOUSANDSSEPARATOR,
    0, //SDLK_DECIMALSEPARATOR,
    0, //SDLK_CURRENCYUNIT,
    0, //SDLK_CURRENCYSUBUNIT,
    SDLK_LEFTPAREN,
    SDLK_RIGHTPAREN,
    SDLK_LEFTBRACKET,
    SDLK_RIGHTBRACKET,
    0, //SDLK_KP_TAB,
    0, //SDLK_KP_BACKSPACE,
    0, //SDLK_KP_A,
    0, //SDLK_KP_B,
    0, //SDLK_KP_C,
    0, //SDLK_KP_D,
    0, //SDLK_KP_E,
    0, //SDLK_KP_F,
    0, //SDLK_KP_XOR,
    0, //SDLK_KP_POWER,
    0, //SDLK_KP_PERCENT,
    SDLK_LESS,
    SDLK_GREATER,
    0, //SDLK_KP_AMPERSAND,
    0, //SDLK_KP_DBLAMPERSAND,
    0, //SDLK_KP_VERTICALBAR,
    0, //SDLK_KP_DBLVERTICALBAR,
    SDLK_COLON,
    SDLK_HASH,
    0, //SDLK_KP_SPACE,
    SDLK_AT,
    SDLK_EXCLAIM,
    0, //SDLK_KP_MEMSTORE,
    0, //SDLK_KP_MEMRECALL,
    0, //SDLK_KP_MEMCLEAR,
    0, //SDLK_KP_MEMADD,
    0, //SDLK_KP_MEMSUBTRACT,
    0, //SDLK_KP_MEMMULTIPLY,
    0, //SDLK_KP_MEMDIVIDE,
    0, //SDLK_KP_PLUSMINUS,
    0, //SDLK_KP_CLEAR,
    0, //SDLK_KP_CLEARENTRY,
    0, //SDLK_KP_BINARY,
    0, //SDLK_KP_OCTAL,
    0, //SDLK_KP_DECIMAL,
    0, //SDLK_KP_HEXADECIMAL,
    0, 0,
    SDLK_LCTRL,
    SDLK_LSHIFT,
    SDLK_LALT,
    SDLK_LSUPER,
    SDLK_RCTRL,
    SDLK_RSHIFT,
    SDLK_RALT,
    SDLK_RSUPER,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, //SDLK_MODE,
    0, //SDLK_AUDIONEXT,
    0, //SDLK_AUDIOPREV,
    0, //SDLK_AUDIOSTOP,
    0, //SDLK_AUDIOPLAY,
    0, //SDLK_AUDIOMUTE,
    0, //SDLK_MEDIASELECT,
    0, //SDLK_WWW,
    0, //SDLK_MAIL,
    0, //SDLK_CALCULATOR,
    0, //SDLK_COMPUTER,
    0, //SDLK_AC_SEARCH,
    0, //SDLK_AC_HOME,
    0, //SDLK_AC_BACK,
    0, //SDLK_AC_FORWARD,
    0, //SDLK_AC_STOP,
    0, //SDLK_AC_REFRESH,
    0, //SDLK_AC_BOOKMARKS,
    0, //SDLK_BRIGHTNESSDOWN,
    0, //SDLK_BRIGHTNESSUP,
    0, //SDLK_DISPLAYSWITCH,
    0, //SDLK_KBDILLUMTOGGLE,
    0, //SDLK_KBDILLUMDOWN,
    0, //SDLK_KBDILLUMUP,
    0, //SDLK_EJECT,
    0, //SDLK_SLEEP,
};

const int keycodes_shift_table[][2] =
{
	{'!', '1'},
	{'@', '2'},
	{'#', '3'},
	{'$', '4'},
	{'%', '5'},
	{'^', '6'},
	{'&', '7'},
	{'*', '8'},
	{'(', '9'},
	{')', '0'},
	{'_', '-'},
	{'+', '='},
	{'|', '\\'},
	{'<', ','},
	{'>', '.'},
	{'?', '/'},
	{':', ';'},
	{'"', '\''},
	{'{', '['},
	{'}', ']'},
	{'~', '`'},
	{'Q', 'q'},
	{'W', 'w'},
	{'E', 'e'},
	{'R', 'r'},
	{'T', 't'},
	{'Y', 'y'},
	{'U', 'u'},
	{'I', 'i'},
	{'O', 'o'},
	{'P', 'p'},
	{'A', 'a'},
	{'S', 's'},
	{'D', 'd'},
	{'F', 'f'},
	{'G', 'g'},
	{'H', 'h'},
	{'J', 'j'},
	{'K', 'k'},
	{'L', 'l'},
	{'Z', 'z'},
	{'X', 'x'},
	{'C', 'c'},
	{'V', 'v'},
	{'B', 'b'},
	{'N', 'n'},
	{'M', 'm'},
	{0, 0},
};
